# Generated by Django 2.1.2 on 2018-10-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mocktest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('method', models.CharField(max_length=10)),
                ('request_body', models.CharField(max_length=500)),
                ('reponse_body', models.CharField(max_length=500)),
                ('time_delay', models.FloatField()),
                ('add_date', models.DateTimeField()),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
