# Generated by Django 2.1.2 on 2018-10-26 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mockmodel', '0002_auto_20181025_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mocktest',
            old_name='reponse_body',
            new_name='response_body',
        ),
    ]
